export interface QuranSurah {
  id: number;
  name: string;
  englishName: string;
  ayahCount: number;
  type: "مكية" | "مدنية";
}

export interface QuranReciter {
  id: string;
  name: string;
  style: string;
  serverUrl: string; // e.g. "https://server8.mp3quran.net/afs"
}

export const QURAN_RECITERS: QuranReciter[] = [
  {
    id: "afs",
    name: "مشاري راشد العفاسي",
    style: "حفص عن عاصم",
    serverUrl: "https://server8.mp3quran.net/afs",
  },
  {
    id: "basit_murattal",
    name: "عبد الباسط عبد الصمد (مرتل)",
    style: "حفص عن عاصم",
    serverUrl: "https://server7.mp3quran.net/basit",
  },
  {
    id: "basit_mujawwad",
    name: "عبد الباسط عبد الصمد (مجود)",
    style: "حفص عن عاصم",
    serverUrl: "https://server7.mp3quran.net/basit_mjwd",
  },
  {
    id: "maher",
    name: "ماهر المعيقلي",
    style: "حفص عن عاصم",
    serverUrl: "https://server12.mp3quran.net/maher",
  },
  {
    id: "shuraim",
    name: "سعود الشريم",
    style: "حفص عن عاصم",
    serverUrl: "https://server7.mp3quran.net/shur",
  },
  {
    id: "ghamdi",
    name: "سعد الغامدي",
    style: "حفص عن عاصم",
    serverUrl: "https://server7.mp3quran.net/s_gmd",
  },
  {
    id: "yasser",
    name: "ياسر الدوسري",
    style: "حفص عن عاصم",
    serverUrl: "https://server11.mp3quran.net/yasser",
  },
  {
    id: "minshawi_murattal",
    name: "محمد صديق المنشاوي (مرتل)",
    style: "حفص عن عاصم",
    serverUrl: "https://server10.mp3quran.net/minsh",
  },
  {
    id: "minshawi_mujawwad",
    name: "محمد صديق المنشاوي (مجود)",
    style: "حفص عن عاصم",
    serverUrl: "https://server10.mp3quran.net/minsh_mjwd",
  },
  {
    id: "hussary",
    name: "محمود خليل الحصري",
    style: "حفص عن عاصم",
    serverUrl: "https://server13.mp3quran.net/husr",
  },
  {
    id: "qatami",
    name: "ناصر القطامي",
    style: "حفص عن عاصم",
    serverUrl: "https://server6.mp3quran.net/qtm",
  },
  {
    id: "shatri",
    name: "أبو بكر الشاطري",
    style: "حفص عن عاصم",
    serverUrl: "https://server11.mp3quran.net/shatri",
  },
  {
    id: "jalil",
    name: "خالد الجليل",
    style: "حفص عن عاصم",
    serverUrl: "https://server10.mp3quran.net/jleel",
  },
  {
    id: "ajmi",
    name: "أحمد العجمي",
    style: "حفص عن عاصم",
    serverUrl: "https://server10.mp3quran.net/ajm",
  },
  {
    id: "abbad",
    name: "فارس عباد",
    style: "حفص عن عاصم",
    serverUrl: "https://server8.mp3quran.net/frs_a",
  },
  {
    id: "abkar",
    name: "إدريس أبكر",
    style: "حفص عن عاصم",
    serverUrl: "https://server6.mp3quran.net/abkr",
  },
  {
    id: "hudhaify",
    name: "علي الحذيفي",
    style: "حفص عن عاصم",
    serverUrl: "https://server9.mp3quran.net/hthfi",
  },
];

export const QURAN_SURAHS: QuranSurah[] = [
  { id: 1, name: "الفاتحة", englishName: "Al-Fatihah", ayahCount: 7, type: "مكية" },
  { id: 2, name: "البقرة", englishName: "Al-Baqarah", ayahCount: 286, type: "مدنية" },
  { id: 3, name: "آل عمران", englishName: "Aal-Imran", ayahCount: 200, type: "مدنية" },
  { id: 4, name: "النساء", englishName: "An-Nisa", ayahCount: 176, type: "مدنية" },
  { id: 5, name: "المائدة", englishName: "Al-Maidah", ayahCount: 120, type: "مدنية" },
  { id: 6, name: "الأنعام", englishName: "Al-Anam", ayahCount: 165, type: "مكية" },
  { id: 7, name: "الأعراف", englishName: "Al-Araf", ayahCount: 206, type: "مكية" },
  { id: 8, name: "الأنفال", englishName: "Al-Anfal", ayahCount: 75, type: "مدنية" },
  { id: 9, name: "التوبة", englishName: "At-Tawbah", ayahCount: 129, type: "مدنية" },
  { id: 10, name: "يونس", englishName: "Yunus", ayahCount: 109, type: "مكية" },
  { id: 11, name: "هود", englishName: "Hud", ayahCount: 123, type: "مكية" },
  { id: 12, name: "يوسف", englishName: "Yusuf", ayahCount: 111, type: "مكية" },
  { id: 13, name: "الرعد", englishName: "Ar-Rad", ayahCount: 43, type: "مدنية" },
  { id: 14, name: "إبراهيم", englishName: "Ibrahim", ayahCount: 52, type: "مكية" },
  { id: 15, name: "الحجر", englishName: "Al-Hijr", ayahCount: 99, type: "مكية" },
  { id: 16, name: "النحل", englishName: "An-Nahl", ayahCount: 128, type: "مكية" },
  { id: 17, name: "الإسراء", englishName: "Al-Isra", ayahCount: 111, type: "مكية" },
  { id: 18, name: "الكهف", englishName: "Al-Kahf", ayahCount: 110, type: "مكية" },
  { id: 19, name: "مريم", englishName: "Maryam", ayahCount: 98, type: "مكية" },
  { id: 20, name: "طه", englishName: "Taha", ayahCount: 135, type: "مكية" },
  { id: 21, name: "الأنبياء", englishName: "Al-Anbiya", ayahCount: 112, type: "مكية" },
  { id: 22, name: "الحج", englishName: "Al-Hajj", ayahCount: 78, type: "مدنية" },
  { id: 23, name: "المؤمنون", englishName: "Al-Muminun", ayahCount: 118, type: "مكية" },
  { id: 24, name: "النور", englishName: "An-Nur", ayahCount: 64, type: "مدنية" },
  { id: 25, name: "الفرقان", englishName: "Al-Furqan", ayahCount: 77, type: "مكية" },
  { id: 26, name: "الشعراء", englishName: "Ash-Shuara", ayahCount: 227, type: "مكية" },
  { id: 27, name: "النمل", englishName: "An-Naml", ayahCount: 93, type: "مكية" },
  { id: 28, name: "القصص", englishName: "Al-Qasas", ayahCount: 88, type: "مكية" },
  { id: 29, name: "العنكبوت", englishName: "Al-Ankabut", ayahCount: 69, type: "مكية" },
  { id: 30, name: "الروم", englishName: "Ar-Rum", ayahCount: 60, type: "مكية" },
  { id: 31, name: "لقمان", englishName: "Luqman", ayahCount: 34, type: "مكية" },
  { id: 32, name: "السجدة", englishName: "As-Sajdah", ayahCount: 30, type: "مكية" },
  { id: 33, name: "الأحزاب", englishName: "Al-Ahzab", ayahCount: 73, type: "مدنية" },
  { id: 34, name: "سبأ", englishName: "Saba", ayahCount: 54, type: "مكية" },
  { id: 35, name: "فاطر", englishName: "Fatir", ayahCount: 45, type: "مكية" },
  { id: 36, name: "يس", englishName: "Ya-Sin", ayahCount: 83, type: "مكية" },
  { id: 37, name: "الصافات", englishName: "As-Saffat", ayahCount: 182, type: "مكية" },
  { id: 38, name: "ص", englishName: "Sad", ayahCount: 88, type: "مكية" },
  { id: 39, name: "الزمر", englishName: "Az-Zumar", ayahCount: 75, type: "مكية" },
  { id: 40, name: "غافر", englishName: "Ghafir", ayahCount: 85, type: "مكية" },
  { id: 41, name: "فصلت", englishName: "Fussilat", ayahCount: 54, type: "مكية" },
  { id: 42, name: "الشورى", englishName: "Ash-Shura", ayahCount: 53, type: "مكية" },
  { id: 43, name: "الزخرف", englishName: "Az-Zukhruf", ayahCount: 89, type: "مكية" },
  { id: 44, name: "الدخان", englishName: "Ad-Dukhan", ayahCount: 59, type: "مكية" },
  { id: 45, name: "الجاثية", englishName: "Al-Jathiyah", ayahCount: 37, type: "مكية" },
  { id: 46, name: "الأحقاف", englishName: "Al-Ahqaf", ayahCount: 35, type: "مكية" },
  { id: 47, name: "محمد", englishName: "Muhammad", ayahCount: 38, type: "مدنية" },
  { id: 48, name: "الفتح", englishName: "Al-Fath", ayahCount: 29, type: "مدنية" },
  { id: 49, name: "الحجرات", englishName: "Al-Hujurat", ayahCount: 18, type: "مدنية" },
  { id: 50, name: "ق", englishName: "Qaf", ayahCount: 45, type: "مكية" },
  { id: 51, name: "الذاريات", englishName: "Adh-Dhariyat", ayahCount: 60, type: "مكية" },
  { id: 52, name: "الطور", englishName: "At-Tur", ayahCount: 49, type: "مكية" },
  { id: 53, name: "النجم", englishName: "An-Najm", ayahCount: 62, type: "مكية" },
  { id: 54, name: "القمر", englishName: "Al-Qamar", ayahCount: 55, type: "مكية" },
  { id: 55, name: "الرحمن", englishName: "Ar-Rahman", ayahCount: 78, type: "مدنية" },
  { id: 56, name: "الواقعة", englishName: "Al-Waqiah", ayahCount: 96, type: "مكية" },
  { id: 57, name: "الحديد", englishName: "Al-Hadid", ayahCount: 29, type: "مدنية" },
  { id: 58, name: "المجادلة", englishName: "Al-Mujadilah", ayahCount: 22, type: "مدنية" },
  { id: 59, name: "الحشر", englishName: "Al-Hashr", ayahCount: 24, type: "مدنية" },
  { id: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", ayahCount: 13, type: "مدنية" },
  { id: 61, name: "الصف", englishName: "As-Saff", ayahCount: 14, type: "مدنية" },
  { id: 62, name: "الجمعة", englishName: "Al-Jumuah", ayahCount: 11, type: "مدنية" },
  { id: 63, name: "المنافقون", englishName: "Al-Munafiqun", ayahCount: 11, type: "مدنية" },
  { id: 64, name: "التغابن", englishName: "At-Taghabun", ayahCount: 18, type: "مدنية" },
  { id: 65, name: "الطلاق", englishName: "At-Talaq", ayahCount: 12, type: "مدنية" },
  { id: 66, name: "التحريم", englishName: "At-Tahrim", ayahCount: 12, type: "مدنية" },
  { id: 67, name: "الملك", englishName: "Al-Mulk", ayahCount: 30, type: "مكية" },
  { id: 68, name: "القلم", englishName: "Al-Qalam", ayahCount: 52, type: "مكية" },
  { id: 69, name: "الحاقة", englishName: "Al-Haqqah", ayahCount: 52, type: "مكية" },
  { id: 70, name: "المعارج", englishName: "Al-Maarij", ayahCount: 44, type: "مكية" },
  { id: 71, name: "نوح", englishName: "Nuh", ayahCount: 28, type: "مكية" },
  { id: 72, name: "الجن", englishName: "Al-Jinn", ayahCount: 28, type: "مكية" },
  { id: 73, name: "المزمل", englishName: "Al-Muzzammil", ayahCount: 20, type: "مكية" },
  { id: 74, name: "المدثر", englishName: "Al-Muddaththir", ayahCount: 56, type: "مكية" },
  { id: 75, name: "القيامة", englishName: "Al-Qiyamah", ayahCount: 40, type: "مكية" },
  { id: 76, name: "الإنسان", englishName: "Al-Insan", ayahCount: 31, type: "مدنية" },
  { id: 77, name: "المرسلات", englishName: "Al-Mursalat", ayahCount: 50, type: "مكية" },
  { id: 78, name: "النبأ", englishName: "An-Naba", ayahCount: 40, type: "مكية" },
  { id: 79, name: "النازعات", englishName: "An-Naziat", ayahCount: 46, type: "مكية" },
  { id: 80, name: "عبس", englishName: "Abasa", ayahCount: 42, type: "مكية" },
  { id: 81, name: "التكوير", englishName: "At-Takwir", ayahCount: 29, type: "مكية" },
  { id: 82, name: "الانفطار", englishName: "Al-Infitar", ayahCount: 19, type: "مكية" },
  { id: 83, name: "المطففين", englishName: "Al-Mutaffifin", ayahCount: 36, type: "مكية" },
  { id: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", ayahCount: 25, type: "مكية" },
  { id: 85, name: "البروج", englishName: "Al-Buruj", ayahCount: 22, type: "مكية" },
  { id: 86, name: "الطارق", englishName: "At-Tariq", ayahCount: 17, type: "مكية" },
  { id: 87, name: "الأعلى", englishName: "Al-Ala", ayahCount: 19, type: "مكية" },
  { id: 88, name: "الغاشية", englishName: "Al-Ghashiyah", ayahCount: 26, type: "مكية" },
  { id: 89, name: "الفجر", englishName: "Al-Fajr", ayahCount: 30, type: "مكية" },
  { id: 90, name: "البلد", englishName: "Al-Balad", ayahCount: 20, type: "مكية" },
  { id: 91, name: "الشمس", englishName: "Ash-Shams", ayahCount: 15, type: "مكية" },
  { id: 92, name: "الليل", englishName: "Al-Layl", ayahCount: 21, type: "مكية" },
  { id: 93, name: "الضحى", englishName: "Ad-Duha", ayahCount: 11, type: "مكية" },
  { id: 94, name: "الشرح", englishName: "Ash-Sharh", ayahCount: 8, type: "مكية" },
  { id: 95, name: "التين", englishName: "At-Tin", ayahCount: 8, type: "مكية" },
  { id: 96, name: "العلق", englishName: "Al-Alaq", ayahCount: 19, type: "مكية" },
  { id: 97, name: "القدر", englishName: "Al-Qadr", ayahCount: 5, type: "مكية" },
  { id: 98, name: "البينة", englishName: "Al-Bayyinah", ayahCount: 8, type: "مدنية" },
  { id: 99, name: "الزلزلة", englishName: "Az-Zalzalah", ayahCount: 8, type: "مدنية" },
  { id: 100, name: "العاديات", englishName: "Al-Adiyat", ayahCount: 11, type: "مكية" },
  { id: 101, name: "القارعة", englishName: "Al-Qariah", ayahCount: 11, type: "مكية" },
  { id: 102, name: "التكاثر", englishName: "At-Takathur", ayahCount: 8, type: "مكية" },
  { id: 103, name: "العصر", englishName: "Al-Asr", ayahCount: 3, type: "مكية" },
  { id: 104, name: "الهمزة", englishName: "Al-Humazah", ayahCount: 9, type: "مكية" },
  { id: 105, name: "الفيل", englishName: "Al-Fil", ayahCount: 5, type: "مكية" },
  { id: 106, name: "قريش", englishName: "Quraysh", ayahCount: 4, type: "مكية" },
  { id: 107, name: "الماعون", englishName: "Al-Maun", ayahCount: 7, type: "مكية" },
  { id: 108, name: "الكوثر", englishName: "Al-Kawthar", ayahCount: 3, type: "مكية" },
  { id: 109, name: "الكافرون", englishName: "Al-Kafirun", ayahCount: 6, type: "مكية" },
  { id: 110, name: "النصر", englishName: "An-Nasr", ayahCount: 3, type: "مدنية" },
  { id: 111, name: "المسد", englishName: "Al-Masad", ayahCount: 5, type: "مكية" },
  { id: 112, name: "الإخلاص", englishName: "Al-Ikhlas", ayahCount: 4, type: "مكية" },
  { id: 113, name: "الفلق", englishName: "Al-Falaq", ayahCount: 5, type: "مكية" },
  { id: 114, name: "الناس", englishName: "An-Nas", ayahCount: 6, type: "مكية" },
];

/**
 * دالة مساعدة لتوليد رابط البث المباشر لسورة بعينها مع قارئ محدد
 */
export function getSurahAudioUrl(serverUrl: string, surahId: number): string {
  const padded = String(surahId).padStart(3, "0");
  const cleanServer = serverUrl.replace(/\/+$/, "");
  return `${cleanServer}/${padded}.mp3`;
}
