// شجرة الحسابات — مصدر البذر TypeScript للاختبارات. الإنتاج يُبذر الأدوار
// الأصلية عبر 0115 وأدوار P2/Sh2 عبر 0184. أبقِ المصدرين متطابقين دائماً.
export interface SeedAccount {
  id: number;
  code: string;
  name: string;
  type: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
  parentId: number | null;
  systemRole: string | null;
  sortOrder: number;
}

export const CHART_ACCOUNTS: SeedAccount[] = [
  {
    id: 1,
    code: "1000",
    name: "الأصول",
    type: "ASSET",
    parentId: null,
    systemRole: null,
    sortOrder: 10,
  },
  {
    id: 2,
    code: "1100",
    name: "الصندوق",
    type: "ASSET",
    parentId: 1,
    systemRole: "CASH",
    sortOrder: 11,
  },
  {
    id: 3,
    code: "1150",
    name: "البطاقة / البنك",
    type: "ASSET",
    parentId: 1,
    systemRole: "CARD_BANK",
    sortOrder: 12,
  },
  {
    id: 4,
    code: "1200",
    name: "المخزون",
    type: "ASSET",
    parentId: 1,
    systemRole: "INVENTORY",
    sortOrder: 13,
  },
  {
    id: 5,
    code: "1300",
    name: "ذمم العملاء (مدينون)",
    type: "ASSET",
    parentId: 1,
    systemRole: "AR",
    sortOrder: 14,
  },
  {
    id: 6,
    code: "1400",
    name: "سلف الموظفين",
    type: "ASSET",
    parentId: 1,
    systemRole: "EMPLOYEE_ADVANCES",
    sortOrder: 15,
  },
  {
    id: 7,
    code: "1500",
    name: "الأصول الثابتة",
    type: "ASSET",
    parentId: 1,
    systemRole: "FIXED_ASSETS",
    sortOrder: 16,
  },
  {
    id: 8,
    code: "2000",
    name: "الالتزامات",
    type: "LIABILITY",
    parentId: null,
    systemRole: null,
    sortOrder: 20,
  },
  {
    id: 9,
    code: "2100",
    name: "ذمم الموردين (دائنون)",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "AP",
    sortOrder: 21,
  },
  {
    id: 10,
    code: "2200",
    name: "ذمم مودِعي الأمانة",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "CONSIGNMENT_PAYABLE",
    sortOrder: 22,
  },
  {
    id: 11,
    code: "2300",
    name: "رواتب مستحقة",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "ACCRUED_SALARY",
    sortOrder: 23,
  },
  {
    id: 12,
    code: "2900",
    name: "التزامات أخرى",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "OTHER_LIABILITY",
    sortOrder: 29,
  },
  {
    id: 13,
    code: "3000",
    name: "حقوق الملكية",
    type: "EQUITY",
    parentId: null,
    systemRole: null,
    sortOrder: 30,
  },
  {
    id: 14,
    code: "3100",
    name: "رأس المال",
    type: "EQUITY",
    parentId: 13,
    systemRole: "CAPITAL",
    sortOrder: 31,
  },
  {
    id: 15,
    code: "3200",
    name: "الأرباح المحتجزة",
    type: "EQUITY",
    parentId: 13,
    systemRole: "RETAINED_EARNINGS",
    sortOrder: 32,
  },
  {
    id: 16,
    code: "3900",
    name: "رصيد افتتاحيّ",
    type: "EQUITY",
    parentId: 13,
    systemRole: "OPENING_EQUITY",
    sortOrder: 39,
  },
  {
    id: 17,
    code: "4000",
    name: "الإيرادات",
    type: "REVENUE",
    parentId: null,
    systemRole: null,
    sortOrder: 40,
  },
  {
    id: 18,
    code: "4100",
    name: "مبيعات القرطاسية والكتب",
    type: "REVENUE",
    parentId: 17,
    systemRole: "SALES_STATIONERY",
    sortOrder: 41,
  },
  {
    id: 19,
    code: "4200",
    name: "إيرادات المطبعة الرقمية",
    type: "REVENUE",
    parentId: 17,
    systemRole: "SALES_PRINT",
    sortOrder: 42,
  },
  {
    id: 20,
    code: "4300",
    name: "إيرادات الفلكس / الطباعة العريضة",
    type: "REVENUE",
    parentId: 17,
    systemRole: "SALES_FLEX",
    sortOrder: 43,
  },
  {
    id: 21,
    code: "4400",
    name: "إيرادات التوصيل",
    type: "REVENUE",
    parentId: 17,
    systemRole: "DELIVERY_REVENUE",
    sortOrder: 44,
  },
  {
    id: 22,
    code: "4500",
    name: "عمولات الصيرفة",
    type: "REVENUE",
    parentId: 17,
    systemRole: "EXCHANGE_COMMISSION",
    sortOrder: 45,
  },
  {
    id: 23,
    code: "4900",
    name: "إيرادات أخرى",
    type: "REVENUE",
    parentId: 17,
    systemRole: "OTHER_REVENUE",
    sortOrder: 49,
  },
  {
    id: 24,
    code: "5000",
    name: "المصروفات",
    type: "EXPENSE",
    parentId: null,
    systemRole: null,
    sortOrder: 50,
  },
  {
    id: 25,
    code: "5100",
    name: "تكلفة المبيعات",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "COGS",
    sortOrder: 51,
  },
  {
    id: 26,
    code: "5200",
    name: "الرواتب والأجور",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "SALARIES",
    sortOrder: 52,
  },
  {
    id: 27,
    code: "5300",
    name: "الإيجار",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "RENT",
    sortOrder: 53,
  },
  {
    id: 28,
    code: "5400",
    name: "الكهرباء والخدمات",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "UTILITIES",
    sortOrder: 54,
  },
  {
    id: 29,
    code: "5500",
    name: "مصروفات تشغيلية عامة",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "OPERATING_EXPENSE",
    sortOrder: 55,
  },
  {
    id: 30,
    code: "5600",
    name: "خسائر (تالف / شحن غير مسترد / فروق)",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "LOSSES",
    sortOrder: 56,
  },
  {
    id: 31,
    code: "5900",
    name: "مصروفات أخرى",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "OTHER_EXPENSE",
    sortOrder: 59,
  },
  // IDs 32+ are deterministic for tests only; migration 0184 lets MySQL allocate production IDs.
  {
    id: 32,
    code: "1110",
    name: "الخزينة",
    type: "ASSET",
    parentId: 1,
    systemRole: "TREASURY_CASH",
    sortOrder: 111,
  },
  {
    id: 33,
    code: "1120",
    name: "نقد في الطريق",
    type: "ASSET",
    parentId: 1,
    systemRole: "CASH_IN_TRANSIT",
    sortOrder: 112,
  },
  {
    id: 34,
    code: "1160",
    name: "عهدة جهات التوصيل",
    type: "ASSET",
    parentId: 1,
    systemRole: "DELIVERY_FLOAT",
    sortOrder: 116,
  },
  {
    id: 35,
    code: "1170",
    name: "محفظة الصيرفة — دينار عراقي",
    type: "ASSET",
    parentId: 1,
    systemRole: "EXCHANGE_WALLET_IQD",
    sortOrder: 117,
  },
  {
    id: 36,
    code: "1180",
    name: "محفظة الصيرفة — دولار بالقيمة الدفترية",
    type: "ASSET",
    parentId: 1,
    systemRole: "EXCHANGE_WALLET_USD",
    sortOrder: 118,
  },
  {
    id: 37,
    code: "1190",
    name: "أرصدة المحافظ الرقمية",
    type: "ASSET",
    parentId: 1,
    systemRole: "DIGITAL_WALLET",
    sortOrder: 119,
  },
  {
    id: 38,
    code: "1590",
    name: "مجمع استهلاك الأصول الثابتة",
    type: "ASSET",
    parentId: 1,
    systemRole: "ACCUMULATED_DEPRECIATION",
    sortOrder: 159,
  },
  {
    id: 39,
    code: "2400",
    name: "مستحقات جهات التوصيل",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "COURIER_PAYABLE",
    sortOrder: 240,
  },
  {
    id: 40,
    code: "2500",
    name: "ضرائب ورسوم مستحقة",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "TAX_PAYABLE",
    sortOrder: 250,
  },
  {
    id: 41,
    code: "2600",
    name: "قروض مستحقة",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "LOAN_PAYABLE",
    sortOrder: 260,
  },
  {
    id: 42,
    code: "3300",
    name: "جاري المالك",
    type: "EQUITY",
    parentId: 13,
    systemRole: "OWNER_CURRENT",
    sortOrder: 330,
  },
  {
    id: 43,
    code: "4600",
    name: "أرباح فروقات الصرف",
    type: "REVENUE",
    parentId: 17,
    systemRole: "FX_GAIN",
    sortOrder: 460,
  },
  {
    id: 44,
    code: "5610",
    name: "أجور التوصيل",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "DELIVERY_EXPENSE",
    sortOrder: 561,
  },
  {
    id: 45,
    code: "5620",
    name: "هدايا وترويج",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "GIFTS_PROMO",
    sortOrder: 562,
  },
  {
    id: 46,
    code: "5630",
    name: "استهلاك الأصول الثابتة",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "DEPRECIATION_EXPENSE",
    sortOrder: 563,
  },
  {
    id: 47,
    code: "5640",
    name: "خسائر فروقات الصرف",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "FX_LOSS",
    sortOrder: 564,
  },
  {
    id: 48,
    code: "5650",
    name: "فروقات التقريب النقدي",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "ROUNDING_DIFF",
    sortOrder: 565,
  },
  {
    id: 49,
    code: "4700",
    name: "أرباح استبعاد الأصول الثابتة",
    type: "REVENUE",
    parentId: 17,
    systemRole: "ASSET_DISPOSAL_GAIN",
    sortOrder: 470,
  },
  {
    id: 50,
    code: "5660",
    name: "خسائر استبعاد الأصول الثابتة",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "ASSET_DISPOSAL_LOSS",
    sortOrder: 566,
  },
  {
    id: 51,
    code: "1185",
    name: "نقد أجنبي — دولار بالقيمة الدفترية",
    type: "ASSET",
    parentId: 1,
    systemRole: "FOREIGN_CASH_USD",
    sortOrder: 1185,
  },
  {
    id: 52,
    code: "1130",
    name: "شيكات قيد التحصيل",
    type: "ASSET",
    parentId: 1,
    systemRole: "CHECKS_RECEIVABLE",
    sortOrder: 113,
  },
  {
    id: 53,
    code: "1140",
    name: "محافظ الدفع والتحصيل",
    type: "ASSET",
    parentId: 1,
    systemRole: "PAYMENT_WALLET",
    sortOrder: 114,
  },
  {
    id: 54,
    code: "1145",
    name: "رصيد اتصالات محصل",
    type: "ASSET",
    parentId: 1,
    systemRole: "TELECOM_BALANCE",
    sortOrder: 1145,
  },
  {
    id: 55,
    code: "5670",
    name: "فروقات كلفة مرتجعات المشتريات",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "PURCHASE_PRICE_VARIANCE",
    sortOrder: 567,
  },
  {
    id: 56,
    code: "1250",
    name: "إنتاج تحت التشغيل",
    type: "ASSET",
    parentId: 1,
    systemRole: "WORK_IN_PROGRESS",
    sortOrder: 125,
  },
  {
    id: 57,
    code: "2310",
    name: "ضريبة دخل الرواتب المستحقة",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "PAYROLL_TAX_PAYABLE",
    sortOrder: 231,
  },
  {
    id: 58,
    code: "2320",
    name: "الضمان الاجتماعي المستحق",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "SOCIAL_SECURITY_PAYABLE",
    sortOrder: 232,
  },
  {
    id: 59,
    code: "2330",
    name: "مخصص نهاية الخدمة",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "EOS_PROVISION",
    sortOrder: 233,
  },
  {
    id: 60,
    code: "2340",
    name: "مصروفات مستحقة غير مدفوعة",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "ACCRUED_EXPENSES",
    sortOrder: 234,
  },
  {
    id: 61,
    code: "5210",
    name: "مصروف الضمان الاجتماعي لصاحب العمل",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "SOCIAL_SECURITY_EXPENSE",
    sortOrder: 521,
  },
  {
    id: 62,
    code: "5220",
    name: "مصروف مخصص نهاية الخدمة",
    type: "EXPENSE",
    parentId: 24,
    systemRole: "EOS_EXPENSE",
    sortOrder: 522,
  },
  {
    id: 63,
    code: "1900",
    name: "تسويات بين الفروع",
    type: "ASSET",
    parentId: 1,
    systemRole: "INTERBRANCH_CLEARING",
    sortOrder: 190,
  },
  {
    id: 64,
    code: "1171",
    name: "ذمم صيرفات مدينة — دينار عراقي",
    type: "ASSET",
    parentId: 1,
    systemRole: "EXCHANGE_RECEIVABLE_IQD",
    sortOrder: 1171,
  },
  {
    id: 65,
    code: "1181",
    name: "ذمم صيرفات مدينة — دولار بالقيمة الدفترية",
    type: "ASSET",
    parentId: 1,
    systemRole: "EXCHANGE_RECEIVABLE_USD",
    sortOrder: 1181,
  },
  {
    id: 66,
    code: "2170",
    name: "ذمم صيرفات دائنة — دينار عراقي",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "EXCHANGE_PAYABLE_IQD",
    sortOrder: 217,
  },
  {
    id: 67,
    code: "2180",
    name: "ذمم صيرفات دائنة — دولار بالقيمة الدفترية",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "EXCHANGE_PAYABLE_USD",
    sortOrder: 218,
  },
  {
    id: 68,
    code: "2150",
    name: "بضاعة مستلمة غير مفوترة (GRNI)",
    type: "LIABILITY",
    parentId: 8,
    systemRole: "GRNI",
    sortOrder: 215,
  },
];
