CREATE TABLE IF NOT EXISTS `storefrontPushDevices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `customerId` BIGINT NULL,
  `tokenHash` CHAR(64) NOT NULL,
  `tokenCiphertext` TEXT NOT NULL,
  `platform` ENUM('IOS','ANDROID') NOT NULL,
  `appVersion` VARCHAR(64) NOT NULL,
  `marketingOptIn` TINYINT(1) NOT NULL DEFAULT 0,
  `transactionalOptIn` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastSeenAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `revokedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_storefront_push_token_hash` (`tokenHash`),
  KEY `idx_storefront_push_active_marketing` (`marketingOptIn`,`revokedAt`),
  KEY `idx_storefront_push_customer` (`customerId`,`revokedAt`),
  CONSTRAINT `fk_storefront_push_customer` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `storefrontPushCampaigns` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(160) NOT NULL,
  `kind` ENUM('MARKETING','TRANSACTIONAL') NOT NULL DEFAULT 'MARKETING',
  `status` ENUM('DRAFT','APPROVED','SCHEDULED','RUNNING','COMPLETED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `title` VARCHAR(80) NOT NULL,
  `body` VARCHAR(180) NOT NULL,
  `destination` VARCHAR(180) NOT NULL,
  `throttlePerMinute` SMALLINT UNSIGNED NOT NULL DEFAULT 120,
  `scheduledAt` TIMESTAMP NULL,
  `approvedBy` INT NULL,
  `createdBy` INT NULL,
  `launchedAt` TIMESTAMP NULL,
  `completedAt` TIMESTAMP NULL,
  `recipientCount` INT UNSIGNED NOT NULL DEFAULT 0,
  `sentCount` INT UNSIGNED NOT NULL DEFAULT 0,
  `openedCount` INT UNSIGNED NOT NULL DEFAULT 0,
  `clickedCount` INT UNSIGNED NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_storefront_push_campaign_due` (`status`,`scheduledAt`),
  CONSTRAINT `fk_storefront_push_campaign_approved_by` FOREIGN KEY (`approvedBy`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_storefront_push_campaign_created_by` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `storefrontPushDeliveries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `campaignId` BIGINT NOT NULL,
  `deviceId` BIGINT NOT NULL,
  `status` ENUM('PENDING','PROCESSING','RETRY','SENT','GONE','FAILED') NOT NULL DEFAULT 'PENDING',
  `attemptCount` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `availableAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lockedAt` TIMESTAMP NULL,
  `providerTicketId` VARCHAR(255) NULL,
  `errorCode` VARCHAR(64) NULL,
  `sentAt` TIMESTAMP NULL,
  `openedAt` TIMESTAMP NULL,
  `clickedAt` TIMESTAMP NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_storefront_push_delivery` (`campaignId`,`deviceId`),
  KEY `idx_storefront_push_delivery_due` (`status`,`availableAt`),
  CONSTRAINT `fk_storefront_push_delivery_campaign` FOREIGN KEY (`campaignId`) REFERENCES `storefrontPushCampaigns`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_storefront_push_delivery_device` FOREIGN KEY (`deviceId`) REFERENCES `storefrontPushDevices`(`id`) ON DELETE CASCADE
);
