-- 0311 — العملاء المحتملون والفرص التشغيلية.
-- المساران مقصوران بالفرع، بنسخة تفاؤلية، ومفاتيح إعادة آمنة، وأحداث تراكمية بلا حذف صلب.

CREATE TABLE IF NOT EXISTS `salesLeads` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `leadNumber` VARCHAR(50) NOT NULL,
  `branchId` BIGINT NOT NULL,
  `source` ENUM('WALK_IN','PHONE','WHATSAPP','INSTAGRAM','FACEBOOK','WEBSITE','REFERRAL','CAMPAIGN','OTHER') NOT NULL,
  `contactName` VARCHAR(255) NOT NULL,
  `companyName` VARCHAR(255) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(320) NULL,
  `customerId` BIGINT NULL,
  `ownerId` INT NOT NULL,
  `nextFollowUpAt` TIMESTAMP NULL,
  `status` ENUM('NEW','CONTACTED','QUALIFIED','DISQUALIFIED','CONVERTED') NOT NULL DEFAULT 'NEW',
  `lastReason` VARCHAR(500) NULL,
  `version` INT NOT NULL DEFAULT 1,
  `createKey` VARCHAR(120) NOT NULL,
  `createHash` CHAR(64) NOT NULL,
  `createdBy` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sales_lead_number` (`leadNumber`),
  UNIQUE KEY `uq_sales_lead_create_key` (`createKey`),
  KEY `idx_sales_lead_branch_status` (`branchId`, `status`),
  KEY `idx_sales_lead_owner_followup` (`ownerId`, `nextFollowUpAt`),
  KEY `idx_sales_lead_customer` (`customerId`),
  CONSTRAINT `fk_sales_lead_branch` FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_sales_lead_customer` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`),
  CONSTRAINT `fk_sales_lead_owner` FOREIGN KEY (`ownerId`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_sales_lead_creator` FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_sales_lead_version` CHECK (`version` > 0),
  CONSTRAINT `chk_sales_lead_contact` CHECK (CHAR_LENGTH(TRIM(`contactName`)) > 0),
  CONSTRAINT `chk_sales_lead_disqualified_reason` CHECK (`status` <> 'DISQUALIFIED' OR `lastReason` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS `salesLeadEvents` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `eventKey` VARCHAR(120) NOT NULL,
  `leadId` BIGINT NOT NULL,
  `branchId` BIGINT NOT NULL,
  `eventType` ENUM('CREATED','UPDATED','STATUS_CHANGED','CONVERTED') NOT NULL,
  `fromStatus` ENUM('NEW','CONTACTED','QUALIFIED','DISQUALIFIED','CONVERTED') NULL,
  `toStatus` ENUM('NEW','CONTACTED','QUALIFIED','DISQUALIFIED','CONVERTED') NULL,
  `baseVersion` INT NOT NULL,
  `resultVersion` INT NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `payload` JSON NOT NULL,
  `payloadHash` CHAR(64) NOT NULL,
  `actorUserId` INT NOT NULL,
  `occurredAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sales_lead_event_key` (`eventKey`),
  KEY `idx_sales_lead_event_lead_time` (`leadId`, `occurredAt`),
  KEY `idx_sales_lead_event_branch_time` (`branchId`, `occurredAt`),
  CONSTRAINT `fk_sales_lead_event_lead` FOREIGN KEY (`leadId`) REFERENCES `salesLeads` (`id`),
  CONSTRAINT `fk_sales_lead_event_branch` FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_sales_lead_event_actor` FOREIGN KEY (`actorUserId`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_sales_lead_event_versions` CHECK (`baseVersion` > 0 AND `resultVersion` >= `baseVersion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS `salesOpportunities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `opportunityNumber` VARCHAR(50) NOT NULL,
  `branchId` BIGINT NOT NULL,
  `leadId` BIGINT NULL,
  `customerId` BIGINT NULL,
  `ownerId` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `stage` ENUM('DISCOVERY','PROPOSAL','NEGOTIATION','WON','LOST') NOT NULL DEFAULT 'DISCOVERY',
  `expectedValue` DECIMAL(15,2) NOT NULL,
  `probability` DECIMAL(5,2) NOT NULL,
  `expectedCloseDate` DATE NOT NULL,
  `quotationId` BIGINT NULL,
  `invoiceId` BIGINT NULL,
  `lastReason` VARCHAR(500) NULL,
  `version` INT NOT NULL DEFAULT 1,
  `createKey` VARCHAR(120) NOT NULL,
  `createHash` CHAR(64) NOT NULL,
  `createdBy` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sales_opp_number` (`opportunityNumber`),
  UNIQUE KEY `uq_sales_opp_create_key` (`createKey`),
  UNIQUE KEY `uq_sales_opp_lead` (`leadId`),
  UNIQUE KEY `uq_sales_opp_quotation` (`quotationId`),
  UNIQUE KEY `uq_sales_opp_invoice` (`invoiceId`),
  KEY `idx_sales_opp_branch_stage` (`branchId`, `stage`),
  KEY `idx_sales_opp_owner_close` (`ownerId`, `expectedCloseDate`),
  KEY `idx_sales_opp_customer` (`customerId`),
  CONSTRAINT `fk_sales_opp_branch` FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_sales_opp_lead` FOREIGN KEY (`leadId`) REFERENCES `salesLeads` (`id`),
  CONSTRAINT `fk_sales_opp_customer` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`),
  CONSTRAINT `fk_sales_opp_owner` FOREIGN KEY (`ownerId`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_sales_opp_quotation` FOREIGN KEY (`quotationId`) REFERENCES `quotations` (`id`),
  CONSTRAINT `fk_sales_opp_invoice` FOREIGN KEY (`invoiceId`) REFERENCES `invoices` (`id`),
  CONSTRAINT `fk_sales_opp_creator` FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_sales_opp_value_probability` CHECK (`expectedValue` >= 0 AND `probability` >= 0 AND `probability` <= 100),
  CONSTRAINT `chk_sales_opp_version` CHECK (`version` > 0),
  CONSTRAINT `chk_sales_opp_party` CHECK (`leadId` IS NOT NULL OR `customerId` IS NOT NULL),
  CONSTRAINT `chk_sales_opp_won_invoice` CHECK ((`stage` = 'WON' AND `invoiceId` IS NOT NULL) OR (`stage` <> 'WON' AND `invoiceId` IS NULL)),
  CONSTRAINT `chk_sales_opp_lost_reason` CHECK (`stage` <> 'LOST' OR `lastReason` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS `salesOpportunityEvents` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `eventKey` VARCHAR(120) NOT NULL,
  `opportunityId` BIGINT NOT NULL,
  `branchId` BIGINT NOT NULL,
  `eventType` ENUM('CREATED','UPDATED','STAGE_CHANGED') NOT NULL,
  `fromStage` ENUM('DISCOVERY','PROPOSAL','NEGOTIATION','WON','LOST') NULL,
  `toStage` ENUM('DISCOVERY','PROPOSAL','NEGOTIATION','WON','LOST') NULL,
  `baseVersion` INT NOT NULL,
  `resultVersion` INT NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `payload` JSON NOT NULL,
  `payloadHash` CHAR(64) NOT NULL,
  `actorUserId` INT NOT NULL,
  `occurredAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sales_opp_event_key` (`eventKey`),
  KEY `idx_sales_opp_event_opp_time` (`opportunityId`, `occurredAt`),
  KEY `idx_sales_opp_event_branch_time` (`branchId`, `occurredAt`),
  CONSTRAINT `fk_sales_opp_event_opp` FOREIGN KEY (`opportunityId`) REFERENCES `salesOpportunities` (`id`),
  CONSTRAINT `fk_sales_opp_event_branch` FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`),
  CONSTRAINT `fk_sales_opp_event_actor` FOREIGN KEY (`actorUserId`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_sales_opp_event_versions` CHECK (`baseVersion` > 0 AND `resultVersion` >= `baseVersion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
