-- 0388: سجل التغذية العكسية ورضا الزبائن والشكاوى التشغيلية والجودة
CREATE TABLE IF NOT EXISTS `customerFeedback` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `customerId` bigint NOT NULL,
  `branchId` bigint,
  `workOrderId` bigint,
  `invoiceId` bigint,
  `rating` int NOT NULL,
  `category` varchar(64) NOT NULL,
  `sentiment` enum('POSITIVE','NEUTRAL','NEGATIVE') NOT NULL DEFAULT 'NEUTRAL',
  `comment` text,
  `issueStatus` enum('NEW','IN_PROGRESS','RESOLVED','CLOSED') NOT NULL DEFAULT 'NEW',
  `rootCauseStation` varchar(64),
  `resolutionAction` text,
  `resolvedBy` int,
  `resolvedAt` timestamp NULL,
  `giftCouponId` bigint,
  `smartGuidance` text,
  `googleReviewInviteSent` boolean NOT NULL DEFAULT false,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `customerFeedback_id` PRIMARY KEY(`id`),
  CONSTRAINT `customerFeedback_customerId_customers_id_fk` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`),
  CONSTRAINT `customerFeedback_branchId_branches_id_fk` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE SET NULL,
  CONSTRAINT `customerFeedback_workOrderId_workOrders_id_fk` FOREIGN KEY (`workOrderId`) REFERENCES `workOrders`(`id`) ON DELETE SET NULL,
  CONSTRAINT `customerFeedback_invoiceId_invoices_id_fk` FOREIGN KEY (`invoiceId`) REFERENCES `invoices`(`id`) ON DELETE SET NULL,
  CONSTRAINT `customerFeedback_resolvedBy_users_id_fk` FOREIGN KEY (`resolvedBy`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  CONSTRAINT `customerFeedback_giftCouponId_coupons_id_fk` FOREIGN KEY (`giftCouponId`) REFERENCES `coupons`(`id`) ON DELETE SET NULL,
  CONSTRAINT `customerFeedback_createdBy_users_id_fk` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`),
  INDEX `idx_cust_feedback_customer` (`customerId`,`createdAt`),
  INDEX `idx_cust_feedback_status` (`issueStatus`,`createdAt`),
  INDEX `idx_cust_feedback_branch` (`branchId`,`createdAt`),
  INDEX `idx_cust_feedback_rating` (`rating`)
);
