import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { ScrollView, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from "react-native";

import { AnimatedEntrance } from "@/components/animated-entrance";
import { ProductReviews } from "@/components/product-reviews";
import { ScreenContainer } from "@/components/screen-container";
import { useCart } from "@/lib/cart-context";
import { formatIqd, formatLatinNumber, productDiscountPercent, useStorefrontProduct } from "@/lib/storefront-api";

export default function ProductDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { addProduct, quantityFor } = useCart();
  const { width } = useWindowDimensions();
  const { product, loading, error } = useStorefrontProduct(Number(id));
  const [selectedImage, setSelectedImage] = useState(0);
  const galleryWidth = width - 32;
  const imageUri = product?.imageUrl ?? null;
  const gallery = useMemo(() => imageUri ? [{ id: "cover", uri: imageUri }] : [], [imageUri]);

  if (loading) return <ScreenContainer className="items-center justify-center px-6" containerClassName="bg-background"><Text style={styles.notFound}>جار تحميل المنتج…</Text></ScreenContainer>;
  if (!product) return <ScreenContainer className="items-center justify-center px-6" containerClassName="bg-background"><Text style={styles.notFound}>{error ?? "المنتج غير متاح"}</Text><TouchableOpacity activeOpacity={0.8} onPress={() => router.back()} style={styles.backSimple}><Text style={styles.backSimpleText}>العودة للمتجر</Text></TouchableOpacity></ScreenContainer>;

  const discount = productDiscountPercent(product);
  const quantity = quantityFor(product.id);
  const addAndStay = () => addProduct(product);

  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <AnimatedEntrance><View style={styles.topbar}><TouchableOpacity activeOpacity={0.8} onPress={() => router.back()} style={styles.iconButton}><MaterialIcons color="#0E806A" name="arrow-forward" size={23} /></TouchableOpacity><Text style={styles.topTitle}>تفاصيل المنتج</Text><TouchableOpacity activeOpacity={0.8} onPress={() => router.push("/cart" as never)} style={styles.iconButton}><MaterialIcons color="#0E806A" name="shopping-bag" size={21} /></TouchableOpacity></View></AnimatedEntrance>
    <AnimatedEntrance delay={55}><View style={styles.galleryWrap}>{gallery.length ? <ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false} onMomentumScrollEnd={(event) => setSelectedImage(Math.round(event.nativeEvent.contentOffset.x / galleryWidth))} style={styles.gallery}>{gallery.map((item) => <View key={item.id} style={[styles.cover, { width: galleryWidth, backgroundColor: product.accent }]}><Image cachePolicy="memory-disk" contentFit="contain" contentPosition="center" priority="high" recyclingKey={item.uri} source={item.uri} style={styles.image} transition={160} />{discount != null && <View style={styles.discount}><Text style={styles.discountText}>وفّر {discount}%</Text></View>}</View>)}</ScrollView> : <View style={[styles.cover, { width: galleryWidth, backgroundColor: product.accent }]}><MaterialIcons color="#0E806A" name={product.icon} size={104} />{discount != null && <View style={styles.discount}><Text style={styles.discountText}>وفّر {discount}%</Text></View>}</View>}<View style={styles.galleryFooter}><Text style={styles.galleryLabel}>{gallery.length ? `صورة ${selectedImage + 1} من ${gallery.length}` : "صورة توضيحية للمنتج"}</Text>{gallery.length > 1 && <View style={styles.dots}>{gallery.map((item, index) => <View key={item.id} style={[styles.dot, selectedImage === index && styles.activeDot]} />)}</View>}</View></View></AnimatedEntrance>
    <AnimatedEntrance delay={110}><View style={styles.card}><View style={styles.metaRow}><View style={styles.status}><MaterialIcons color="#0E806A" name="check-circle" size={14} /><Text style={styles.statusText}>{product.availability}</Text></View>{product.isBundle && <View style={styles.bundle}><MaterialIcons color="#A56B10" name="inventory-2" size={13} /><Text style={styles.bundleText}>مجموعة</Text></View>}</View><Text style={styles.title}>{product.title}</Text><Text style={styles.brand}>{product.brand ?? product.subtitle}</Text><View style={styles.priceRow}><View><Text style={styles.price}>{formatIqd(product.salePrice ?? product.price)}</Text>{discount != null && <Text style={styles.oldPrice}>{formatIqd(product.price)}</Text>}</View>{product.promotionName && <View style={styles.promo}><MaterialIcons color="#C35445" name="local-offer" size={15} /><Text numberOfLines={1} style={styles.promoText}>{product.promotionName}</Text></View>}</View><View style={styles.divider} /><Text style={styles.descriptionTitle}>عن هذا المنتج</Text><Text style={styles.description}>{product.description}</Text>{product.stockLeft != null && product.stockLeft <= 5 && <View style={styles.stock}><MaterialIcons color="#A56B10" name="inventory" size={20} /><Text style={styles.stockText}>يتبقى {formatLatinNumber(product.stockLeft)} فقط وفق التوفر الحالي.</Text></View>}<View style={styles.info}><MaterialIcons color="#0E806A" name="verified-user" size={20} /><Text style={styles.infoText}>السعر والتوفر يعادان من نظام المكتبة عند إرسال الطلب لحماية حقك في السعر الصحيح.</Text></View><ProductReviews productId={product.productId ?? Number(product.id)} /></View></AnimatedEntrance>
    <AnimatedEntrance delay={165}><View style={styles.purchaseRow}><TouchableOpacity accessibilityLabel="فتح السلة" activeOpacity={0.88} onPress={() => router.push("/cart" as never)} style={styles.addOnly}><MaterialIcons color="#0E806A" name="shopping-bag" size={20} /></TouchableOpacity><TouchableOpacity accessibilityLabel={`إضافة ${product.title} إلى السلة. الكمية الحالية ${formatLatinNumber(quantity)}`} activeOpacity={0.9} onPress={addAndStay} style={styles.add}><Text style={styles.addText}>{quantity > 0 ? `أضف المزيد · ${formatLatinNumber(quantity)}` : "أضف للسلة واستمر بالتسوق"}</Text><MaterialIcons color="#FFFFFF" name={quantity > 0 ? "add" : "add-shopping-cart"} size={20} /></TouchableOpacity></View><Text style={styles.footer}>{quantity > 0 ? `الكمية الحالية في السلة: ${formatLatinNumber(quantity)}` : "يمكنك مراجعة الكمية والتوصيل قبل تأكيد أي طلب."}</Text></AnimatedEntrance>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 16, paddingBottom: 34 }, topbar: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between", marginBottom: 16 }, iconButton: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#EEE3D7", borderRadius: 15, borderWidth: 1, elevation: 2, height: 46, justifyContent: "center", width: 46 }, topTitle: { color: "#183D36", fontFamily: "Cairo_800ExtraBold", fontSize: 16 },
  galleryWrap: { backgroundColor: "#FFFFFF", borderColor: "#EEE3D7", borderRadius: 25, borderWidth: 1, overflow: "hidden" }, gallery: { width: "100%" }, cover: { alignItems: "center", height: 292, justifyContent: "center", overflow: "hidden" }, image: { height: "100%", width: "100%" }, discount: { backgroundColor: "#F05D53", borderRadius: 12, left: 14, paddingHorizontal: 11, paddingVertical: 7, position: "absolute", top: 14 }, discountText: { color: "#FFFFFF", fontFamily: "Cairo_800ExtraBold", fontSize: 12 }, galleryFooter: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between", minHeight: 42, paddingHorizontal: 14 }, galleryLabel: { color: "#708078", fontFamily: "Cairo_600SemiBold", fontSize: 10 }, dots: { flexDirection: "row", gap: 5 }, dot: { backgroundColor: "#D7CBBE", borderRadius: 4, height: 6, width: 6 }, activeDot: { backgroundColor: "#0E806A", width: 17 },
  card: { backgroundColor: "#FFFFFF", borderColor: "#EEE3D7", borderRadius: 23, borderWidth: 1, marginTop: 14, padding: 17 }, metaRow: { flexDirection: "row-reverse", gap: 7, justifyContent: "flex-start" }, status: { alignItems: "center", backgroundColor: "#E8F5EF", borderRadius: 11, flexDirection: "row-reverse", gap: 4, paddingHorizontal: 9, paddingVertical: 5 }, statusText: { color: "#0E806A", fontFamily: "Cairo_700Bold", fontSize: 11 }, bundle: { alignItems: "center", backgroundColor: "#FFF0D9", borderRadius: 11, flexDirection: "row-reverse", gap: 4, paddingHorizontal: 9, paddingVertical: 5 }, bundleText: { color: "#825D10", fontFamily: "Cairo_700Bold", fontSize: 11 }, title: { color: "#183D36", fontFamily: "Cairo_800ExtraBold", fontSize: 24, lineHeight: 34, marginTop: 13, textAlign: "right" }, brand: { color: "#6D817A", fontFamily: "Cairo_400Regular", fontSize: 13, marginTop: 5, textAlign: "right" }, priceRow: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between", marginTop: 16 }, price: { color: "#0E806A", fontFamily: "Cairo_800ExtraBold", fontSize: 22, textAlign: "right" }, oldPrice: { color: "#96A39D", fontFamily: "Cairo_400Regular", fontSize: 12, marginTop: 2, textAlign: "right", textDecorationLine: "line-through" }, promo: { alignItems: "center", backgroundColor: "#FFF0E8", borderRadius: 12, flexDirection: "row-reverse", gap: 5, maxWidth: "52%", paddingHorizontal: 9, paddingVertical: 7 }, promoText: { color: "#B94E3F", fontFamily: "Cairo_700Bold", fontSize: 10 }, divider: { backgroundColor: "#F0E8DE", height: 1, marginVertical: 18 }, descriptionTitle: { color: "#183D36", fontFamily: "Cairo_800ExtraBold", fontSize: 15, textAlign: "right" }, description: { color: "#50675E", fontFamily: "Cairo_400Regular", fontSize: 13, lineHeight: 23, marginTop: 7, textAlign: "right" }, stock: { alignItems: "flex-start", backgroundColor: "#FFF5DD", borderRadius: 15, flexDirection: "row-reverse", gap: 8, marginTop: 16, padding: 12 }, stockText: { color: "#805C12", flex: 1, fontFamily: "Cairo_600SemiBold", fontSize: 11, lineHeight: 18, textAlign: "right" }, info: { alignItems: "flex-start", backgroundColor: "#E8F5EF", borderRadius: 15, flexDirection: "row-reverse", gap: 8, marginTop: 14, padding: 12 }, infoText: { color: "#375D50", flex: 1, fontFamily: "Cairo_600SemiBold", fontSize: 11, lineHeight: 18, textAlign: "right" },
  reviewBox: { alignItems: "flex-start", backgroundColor: "#FFF7E7", borderRadius: 15, flexDirection: "row-reverse", gap: 9, marginTop: 14, padding: 12 }, reviewIcon: { alignItems: "center", backgroundColor: "#FFF0CE", borderRadius: 12, height: 34, justifyContent: "center", width: 34 }, reviewCopy: { flex: 1 }, reviewTitle: { color: "#6F531A", fontFamily: "Cairo_800ExtraBold", fontSize: 12, textAlign: "right" }, reviewText: { color: "#7E6B46", fontFamily: "Cairo_400Regular", fontSize: 10, lineHeight: 17, marginTop: 3, textAlign: "right" },
  purchaseRow: { flexDirection: "row-reverse", gap: 10, marginTop: 16 }, add: { alignItems: "center", backgroundColor: "#0E806A", borderRadius: 17, flex: 1, flexDirection: "row", gap: 8, height: 57, justifyContent: "center" }, addText: { color: "#FFFFFF", fontFamily: "Cairo_800ExtraBold", fontSize: 15 }, addOnly: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#0E806A", borderRadius: 17, borderWidth: 1, height: 57, justifyContent: "center", width: 57 }, footer: { color: "#73827C", fontFamily: "Cairo_400Regular", fontSize: 10, marginTop: 9, textAlign: "center" }, notFound: { color: "#183D36", fontFamily: "Cairo_800ExtraBold", fontSize: 18 }, backSimple: { backgroundColor: "#0E806A", borderRadius: 13, marginTop: 16, paddingHorizontal: 18, paddingVertical: 11 }, backSimpleText: { color: "#FFFFFF", fontFamily: "Cairo_700Bold" },
});
